version: 2
jobs:
  build:
    working_directory: ~/codeknightly
    docker:
      - image: circleci/ruby:2.5.1
      envirnment:
        RAILS_ENV: test
    steps:
      - checkout
                                                 