version: 2
jobs:
  build:
    working_directory: ~/codeknightly
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          PGHOST: localhost
          PGUSER: codeknightly
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: codeknightly
          POSTGREST_DB: codeknightly_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      
      - run:     
          name: Run rspec
          command: bundle exec rspec
                                                 